#[cfg(feature = "_8bit_timer_counter_1")]
pub mod _8bit_timer_counter_1;
#[cfg(feature = "adc10_1")]
pub mod adc10_1;
#[cfg(feature = "adc10_2")]
pub mod adc10_2;
#[cfg(feature = "adc10_3")]
pub mod adc10_3;
#[cfg(feature = "adc10_4")]
pub mod adc10_4;
#[cfg(feature = "adc10_a_1")]
pub mod adc10_a_1;
#[cfg(feature = "adc10_b_1")]
pub mod adc10_b_1;
#[cfg(feature = "adc12_1")]
pub mod adc12_1;
#[cfg(feature = "adc12_2")]
pub mod adc12_2;
#[cfg(feature = "adc12_3")]
pub mod adc12_3;
#[cfg(feature = "adc12_b_3670")]
pub mod adc12_b_3670;
#[cfg(feature = "adc_1")]
pub mod adc_1;
#[cfg(feature = "adc_2")]
pub mod adc_2;
#[cfg(feature = "adc_445")]
pub mod adc_445;
#[cfg(feature = "aes256_3670")]
pub mod aes256_3670;
#[cfg(feature = "aes_accelerator_1")]
pub mod aes_accelerator_1;
#[cfg(feature = "aes_accelerator_2")]
pub mod aes_accelerator_2;
#[cfg(feature = "analog_pool_1")]
pub mod analog_pool_1;
#[cfg(feature = "auxilary_supply_1")]
pub mod auxilary_supply_1;
#[cfg(feature = "backup_memory_1")]
pub mod backup_memory_1;
#[cfg(feature = "backup_ram_1")]
pub mod backup_ram_1;
#[cfg(feature = "basic_timer_1")]
pub mod basic_timer_1;
#[cfg(feature = "basic_timer___rtc_1")]
pub mod basic_timer___rtc_1;
#[cfg(feature = "battery_charger_1")]
pub mod battery_charger_1;
#[cfg(feature = "bkmem_44508")]
pub mod bkmem_44508;
#[cfg(feature = "calibration_data_1")]
pub mod calibration_data_1;
#[cfg(feature = "calibration_data_2")]
pub mod calibration_data_2;
#[cfg(feature = "calibration_data_3")]
pub mod calibration_data_3;
#[cfg(feature = "capacitive_touch_io_0_1")]
pub mod capacitive_touch_io_0_1;
#[cfg(feature = "capacitive_touch_io_1_1")]
pub mod capacitive_touch_io_1_1;
#[cfg(feature = "captio0_3670")]
pub mod captio0_3670;
#[cfg(feature = "captio1_3670")]
pub mod captio1_3670;
#[cfg(feature = "captio_3670")]
pub mod captio_3670;
#[cfg(feature = "captivate_1")]
pub mod captivate_1;
#[cfg(feature = "captivate_100")]
pub mod captivate_100;
#[cfg(feature = "captivate_445_inst4")]
pub mod captivate_445_inst4;
#[cfg(feature = "cc1101_radio_interface_1")]
pub mod cc1101_radio_interface_1;
#[cfg(feature = "ccs__compact_system_clock_1")]
pub mod ccs__compact_system_clock_1;
#[cfg(feature = "comp_e_3670")]
pub mod comp_e_3670;
#[cfg(feature = "comparator_a_1")]
pub mod comparator_a_1;
#[cfg(feature = "comparator_a_2")]
pub mod comparator_a_2;
#[cfg(feature = "comparator_b_1")]
pub mod comparator_b_1;
#[cfg(feature = "comparator_d_1")]
pub mod comparator_d_1;
#[cfg(feature = "comparator_e_1")]
pub mod comparator_e_1;
#[cfg(feature = "crc16_1")]
pub mod crc16_1;
#[cfg(feature = "crc16_2")]
pub mod crc16_2;
#[cfg(feature = "crc32_1")]
pub mod crc32_1;
#[cfg(feature = "crc32_3670")]
pub mod crc32_3670;
#[cfg(feature = "crc_2080")]
pub mod crc_2080;
#[cfg(feature = "cs_3670")]
pub mod cs_3670;
#[cfg(feature = "cs_445")]
pub mod cs_445;
#[cfg(feature = "cs__clock_system_1")]
pub mod cs__clock_system_1;
#[cfg(feature = "cs__clock_system_2")]
pub mod cs__clock_system_2;
#[cfg(feature = "cs__clock_system_3")]
pub mod cs__clock_system_3;
#[cfg(feature = "cs__clock_system_4")]
pub mod cs__clock_system_4;
#[cfg(feature = "cs__clock_system_5")]
pub mod cs__clock_system_5;
#[cfg(feature = "csys__compact_system_module_1")]
pub mod csys__compact_system_module_1;
#[cfg(feature = "csys__compact_system_module_2")]
pub mod csys__compact_system_module_2;
#[cfg(feature = "ctsd16_b4_1")]
pub mod ctsd16_b4_1;
#[cfg(feature = "dac12_1")]
pub mod dac12_1;
#[cfg(feature = "dac12_2")]
pub mod dac12_2;
#[cfg(feature = "dac12_3")]
pub mod dac12_3;
#[cfg(feature = "dac12_4")]
pub mod dac12_4;
#[cfg(feature = "dma_1")]
pub mod dma_1;
#[cfg(feature = "dma_10")]
pub mod dma_10;
#[cfg(feature = "dma_11")]
pub mod dma_11;
#[cfg(feature = "dma_12")]
pub mod dma_12;
#[cfg(feature = "dma_13")]
pub mod dma_13;
#[cfg(feature = "dma_14")]
pub mod dma_14;
#[cfg(feature = "dma_15")]
pub mod dma_15;
#[cfg(feature = "dma_16")]
pub mod dma_16;
#[cfg(feature = "dma_17")]
pub mod dma_17;
#[cfg(feature = "dma_18")]
pub mod dma_18;
#[cfg(feature = "dma_19")]
pub mod dma_19;
#[cfg(feature = "dma_2")]
pub mod dma_2;
#[cfg(feature = "dma_3")]
pub mod dma_3;
#[cfg(feature = "dma_4")]
pub mod dma_4;
#[cfg(feature = "dma_5")]
pub mod dma_5;
#[cfg(feature = "dma_6")]
pub mod dma_6;
#[cfg(feature = "dma_7")]
pub mod dma_7;
#[cfg(feature = "dma_8")]
pub mod dma_8;
#[cfg(feature = "dma_9")]
pub mod dma_9;
#[cfg(feature = "ecomp0_445")]
pub mod ecomp0_445;
#[cfg(feature = "ecomp1_445")]
pub mod ecomp1_445;
#[cfg(feature = "eprom_1")]
pub mod eprom_1;
#[cfg(feature = "espctl_1")]
pub mod espctl_1;
#[cfg(feature = "espctl_2")]
pub mod espctl_2;
#[cfg(feature = "espctl_3")]
pub mod espctl_3;
#[cfg(feature = "eusci_a0_2080")]
pub mod eusci_a0_2080;
#[cfg(feature = "eusci_a0_445")]
pub mod eusci_a0_445;
#[cfg(feature = "eusci_a1_2080")]
pub mod eusci_a1_2080;
#[cfg(feature = "eusci_a1_445")]
pub mod eusci_a1_445;
#[cfg(feature = "eusci_a2_2080")]
pub mod eusci_a2_2080;
#[cfg(feature = "eusci_a3_2080")]
pub mod eusci_a3_2080;
#[cfg(feature = "eusci_b0_2080")]
pub mod eusci_b0_2080;
#[cfg(feature = "eusci_b0_445")]
pub mod eusci_b0_445;
#[cfg(feature = "eusci_b1_2080")]
pub mod eusci_b1_2080;
#[cfg(feature = "eusci_b1_445")]
pub mod eusci_b1_445;
#[cfg(feature = "eusci_b2_2080")]
pub mod eusci_b2_2080;
#[cfg(feature = "eusci_b3_2080")]
pub mod eusci_b3_2080;
#[cfg(feature = "extscanif_1")]
pub mod extscanif_1;
#[cfg(feature = "extscanif_ram_1")]
pub mod extscanif_ram_1;
#[cfg(feature = "flash_1")]
pub mod flash_1;
#[cfg(feature = "flash_2")]
pub mod flash_2;
#[cfg(feature = "flash_3")]
pub mod flash_3;
#[cfg(feature = "flash_4")]
pub mod flash_4;
#[cfg(feature = "flash_5")]
pub mod flash_5;
#[cfg(feature = "flash_6")]
pub mod flash_6;
#[cfg(feature = "flash_7")]
pub mod flash_7;
#[cfg(feature = "fram_1")]
pub mod fram_1;
#[cfg(feature = "fram_2")]
pub mod fram_2;
#[cfg(feature = "frctl_3670")]
pub mod frctl_3670;
#[cfg(feature = "frctl_a_3670")]
pub mod frctl_a_3670;
#[cfg(feature = "hspll_3670")]
pub mod hspll_3670;
#[cfg(feature = "icc_445")]
pub mod icc_445;
#[cfg(feature = "lcd_1")]
pub mod lcd_1;
#[cfg(feature = "lcd_2")]
pub mod lcd_2;
#[cfg(feature = "lcd_a_1")]
pub mod lcd_a_1;
#[cfg(feature = "lcd_b_1")]
pub mod lcd_b_1;
#[cfg(feature = "lcd_c_1")]
pub mod lcd_c_1;
#[cfg(feature = "lcd_c_2")]
pub mod lcd_c_2;
#[cfg(feature = "lcd_c_2080")]
pub mod lcd_c_2080;
#[cfg(feature = "lcd_e_1")]
pub mod lcd_e_1;
#[cfg(feature = "lea_3670")]
pub mod lea_3670;
#[cfg(feature = "lea_sc_3670")]
pub mod lea_sc_3670;
#[cfg(feature = "mpu_1")]
pub mod mpu_1;
#[cfg(feature = "mpu_2")]
pub mod mpu_2;
#[cfg(feature = "mpu_3670")]
pub mod mpu_3670;
#[cfg(feature = "mpy32_2080")]
pub mod mpy32_2080;
#[cfg(feature = "mpy_16__multiplier__16_bit_mode_1")]
pub mod mpy_16__multiplier__16_bit_mode_1;
#[cfg(feature = "mpy_32__multiplier__32_bit_mode_1")]
pub mod mpy_32__multiplier__32_bit_mode_1;
#[cfg(feature = "mtif_3670")]
pub mod mtif_3670;
#[cfg(feature = "multiplier_1")]
pub mod multiplier_1;
#[cfg(feature = "multiplier__16_bit_mode_1")]
pub mod multiplier__16_bit_mode_1;
#[cfg(feature = "multiplier__32_bit_mode_1")]
pub mod multiplier__32_bit_mode_1;
#[cfg(feature = "operational_amplifier_0_1")]
pub mod operational_amplifier_0_1;
#[cfg(feature = "operational_amplifier_1")]
pub mod operational_amplifier_1;
#[cfg(feature = "operational_amplifier_1_1")]
pub mod operational_amplifier_1_1;
#[cfg(feature = "operational_amplifier_2")]
pub mod operational_amplifier_2;
#[cfg(feature = "operational_amplifier_3")]
pub mod operational_amplifier_3;
#[cfg(feature = "operational_amplifier_4")]
pub mod operational_amplifier_4;
#[cfg(feature = "p10_2720")]
pub mod p10_2720;
#[cfg(feature = "p1_2720")]
pub mod p1_2720;
#[cfg(feature = "p2_2720")]
pub mod p2_2720;
#[cfg(feature = "p3_2720")]
pub mod p3_2720;
#[cfg(feature = "p4_2720")]
pub mod p4_2720;
#[cfg(feature = "p5_2720")]
pub mod p5_2720;
#[cfg(feature = "p6_2720")]
pub mod p6_2720;
#[cfg(feature = "p7_2720")]
pub mod p7_2720;
#[cfg(feature = "p8_2720")]
pub mod p8_2720;
#[cfg(feature = "p9_2720")]
pub mod p9_2720;
#[cfg(feature = "pa_2720")]
pub mod pa_2720;
#[cfg(feature = "pb_2720")]
pub mod pb_2720;
#[cfg(feature = "pc_2720")]
pub mod pc_2720;
#[cfg(feature = "pd_2720")]
pub mod pd_2720;
#[cfg(feature = "pe_2720")]
pub mod pe_2720;
#[cfg(feature = "pj_2720")]
pub mod pj_2720;
#[cfg(feature = "pmm_3670")]
pub mod pmm_3670;
#[cfg(feature = "pmm_445")]
pub mod pmm_445;
#[cfg(feature = "pmm_45")]
pub mod pmm_45;
#[cfg(feature = "pmm__power_management_system_1")]
pub mod pmm__power_management_system_1;
#[cfg(feature = "pmm__power_management_system_2")]
pub mod pmm__power_management_system_2;
#[cfg(feature = "pmm__power_management_system_3")]
pub mod pmm__power_management_system_3;
#[cfg(feature = "pmm__power_management_system_4")]
pub mod pmm__power_management_system_4;
#[cfg(feature = "pmm__power_management_system_5")]
pub mod pmm__power_management_system_5;
#[cfg(feature = "pmm__power_management_system_6")]
pub mod pmm__power_management_system_6;
#[cfg(feature = "pmm__power_management_system_7")]
pub mod pmm__power_management_system_7;
#[cfg(feature = "port_0_1")]
pub mod port_0_1;
#[cfg(feature = "port_11_1")]
pub mod port_11_1;
#[cfg(feature = "port_11_2")]
pub mod port_11_2;
#[cfg(feature = "port_1_2_1")]
pub mod port_1_2_1;
#[cfg(feature = "port_1_2_10")]
pub mod port_1_2_10;
#[cfg(feature = "port_1_2_2")]
pub mod port_1_2_2;
#[cfg(feature = "port_1_2_3")]
pub mod port_1_2_3;
#[cfg(feature = "port_1_2_4")]
pub mod port_1_2_4;
#[cfg(feature = "port_1_2_5")]
pub mod port_1_2_5;
#[cfg(feature = "port_1_2_6")]
pub mod port_1_2_6;
#[cfg(feature = "port_1_2_7")]
pub mod port_1_2_7;
#[cfg(feature = "port_1_2_8")]
pub mod port_1_2_8;
#[cfg(feature = "port_1_2_9")]
pub mod port_1_2_9;
#[cfg(feature = "port_3_1")]
pub mod port_3_1;
#[cfg(feature = "port_3_2")]
pub mod port_3_2;
#[cfg(feature = "port_3_3")]
pub mod port_3_3;
#[cfg(feature = "port_3_4_1")]
pub mod port_3_4_1;
#[cfg(feature = "port_3_4_10")]
pub mod port_3_4_10;
#[cfg(feature = "port_3_4_2")]
pub mod port_3_4_2;
#[cfg(feature = "port_3_4_3")]
pub mod port_3_4_3;
#[cfg(feature = "port_3_4_4")]
pub mod port_3_4_4;
#[cfg(feature = "port_3_4_5")]
pub mod port_3_4_5;
#[cfg(feature = "port_3_4_6")]
pub mod port_3_4_6;
#[cfg(feature = "port_3_4_7")]
pub mod port_3_4_7;
#[cfg(feature = "port_3_4_8")]
pub mod port_3_4_8;
#[cfg(feature = "port_3_4_9")]
pub mod port_3_4_9;
#[cfg(feature = "port_5_1")]
pub mod port_5_1;
#[cfg(feature = "port_5_2")]
pub mod port_5_2;
#[cfg(feature = "port_5_6_1")]
pub mod port_5_6_1;
#[cfg(feature = "port_5_6_2")]
pub mod port_5_6_2;
#[cfg(feature = "port_5_6_3")]
pub mod port_5_6_3;
#[cfg(feature = "port_5_6_4")]
pub mod port_5_6_4;
#[cfg(feature = "port_5_6_5")]
pub mod port_5_6_5;
#[cfg(feature = "port_5_6_6")]
pub mod port_5_6_6;
#[cfg(feature = "port_5_6_7")]
pub mod port_5_6_7;
#[cfg(feature = "port_7_1")]
pub mod port_7_1;
#[cfg(feature = "port_7_2")]
pub mod port_7_2;
#[cfg(feature = "port_7_3")]
pub mod port_7_3;
#[cfg(feature = "port_7_8_1")]
pub mod port_7_8_1;
#[cfg(feature = "port_7_8_2")]
pub mod port_7_8_2;
#[cfg(feature = "port_7_8_3")]
pub mod port_7_8_3;
#[cfg(feature = "port_7_8_4")]
pub mod port_7_8_4;
#[cfg(feature = "port_7_8_5")]
pub mod port_7_8_5;
#[cfg(feature = "port_7_8_6")]
pub mod port_7_8_6;
#[cfg(feature = "port_9_1")]
pub mod port_9_1;
#[cfg(feature = "port_9_10_1")]
pub mod port_9_10_1;
#[cfg(feature = "port_9_10_2")]
pub mod port_9_10_2;
#[cfg(feature = "port_9_10_3")]
pub mod port_9_10_3;
#[cfg(feature = "port_9_10_4")]
pub mod port_9_10_4;
#[cfg(feature = "port_9_10_5")]
pub mod port_9_10_5;
#[cfg(feature = "port_9_2")]
pub mod port_9_2;
#[cfg(feature = "port_a_1")]
pub mod port_a_1;
#[cfg(feature = "port_a_2")]
pub mod port_a_2;
#[cfg(feature = "port_a_3")]
pub mod port_a_3;
#[cfg(feature = "port_a_4")]
pub mod port_a_4;
#[cfg(feature = "port_a_5")]
pub mod port_a_5;
#[cfg(feature = "port_a_6")]
pub mod port_a_6;
#[cfg(feature = "port_b_1")]
pub mod port_b_1;
#[cfg(feature = "port_b_2")]
pub mod port_b_2;
#[cfg(feature = "port_b_3")]
pub mod port_b_3;
#[cfg(feature = "port_b_4")]
pub mod port_b_4;
#[cfg(feature = "port_b_5")]
pub mod port_b_5;
#[cfg(feature = "port_b_6")]
pub mod port_b_6;
#[cfg(feature = "port_c_1")]
pub mod port_c_1;
#[cfg(feature = "port_c_2")]
pub mod port_c_2;
#[cfg(feature = "port_c_3")]
pub mod port_c_3;
#[cfg(feature = "port_c_4")]
pub mod port_c_4;
#[cfg(feature = "port_c_5")]
pub mod port_c_5;
#[cfg(feature = "port_d_1")]
pub mod port_d_1;
#[cfg(feature = "port_d_2")]
pub mod port_d_2;
#[cfg(feature = "port_d_3")]
pub mod port_d_3;
#[cfg(feature = "port_d_4")]
pub mod port_d_4;
#[cfg(feature = "port_d_5")]
pub mod port_d_5;
#[cfg(feature = "port_e_1")]
pub mod port_e_1;
#[cfg(feature = "port_e_2")]
pub mod port_e_2;
#[cfg(feature = "port_e_3")]
pub mod port_e_3;
#[cfg(feature = "port_e_4")]
pub mod port_e_4;
#[cfg(feature = "port_f_1")]
pub mod port_f_1;
#[cfg(feature = "port_f_2")]
pub mod port_f_2;
#[cfg(feature = "port_j_1")]
pub mod port_j_1;
#[cfg(feature = "port_j_2")]
pub mod port_j_2;
#[cfg(feature = "port_j_3")]
pub mod port_j_3;
#[cfg(feature = "port_j_4")]
pub mod port_j_4;
#[cfg(feature = "port_j_5")]
pub mod port_j_5;
#[cfg(feature = "port_mapping_control_1")]
pub mod port_mapping_control_1;
#[cfg(feature = "port_mapping_port_1_1")]
pub mod port_mapping_port_1_1;
#[cfg(feature = "port_mapping_port_2_1")]
pub mod port_mapping_port_2_1;
#[cfg(feature = "port_mapping_port_3_1")]
pub mod port_mapping_port_3_1;
#[cfg(feature = "port_mapping_port_4_1")]
pub mod port_mapping_port_4_1;
#[cfg(feature = "port_u_control_1")]
pub mod port_u_control_1;
#[cfg(feature = "ramctl_3670_config1")]
pub mod ramctl_3670_config1;
#[cfg(feature = "ramctl_3670_config2")]
pub mod ramctl_3670_config2;
#[cfg(feature = "rc__ram_control_module_1")]
pub mod rc__ram_control_module_1;
#[cfg(feature = "rc__ram_control_module_2")]
pub mod rc__ram_control_module_2;
#[cfg(feature = "rc__ram_control_module_fram_1")]
pub mod rc__ram_control_module_fram_1;
#[cfg(feature = "realtime_clock_1")]
pub mod realtime_clock_1;
#[cfg(feature = "ref_a_3670")]
pub mod ref_a_3670;
#[cfg(feature = "rf13m_module_1")]
pub mod rf13m_module_1;
#[cfg(feature = "rtc_445")]
pub mod rtc_445;
#[cfg(feature = "rtc__real_time_clock_1")]
pub mod rtc__real_time_clock_1;
#[cfg(feature = "rtc_b__real_time_clock_1")]
pub mod rtc_b__real_time_clock_1;
#[cfg(feature = "rtc_c_2080")]
pub mod rtc_c_2080;
#[cfg(feature = "rtc_c__real_time_clock_1")]
pub mod rtc_c__real_time_clock_1;
#[cfg(feature = "rtc_c__real_time_clock_2")]
pub mod rtc_c__real_time_clock_2;
#[cfg(feature = "rtc_c__real_time_clock_3")]
pub mod rtc_c__real_time_clock_3;
#[cfg(feature = "rtc_ce__real_time_clock_1")]
pub mod rtc_ce__real_time_clock_1;
#[cfg(feature = "rtc_ce__real_time_clock_2")]
pub mod rtc_ce__real_time_clock_2;
#[cfg(feature = "rtc_d__real_time_clock_1")]
pub mod rtc_d__real_time_clock_1;
#[cfg(feature = "sac0_45508_config1")]
pub mod sac0_45508_config1;
#[cfg(feature = "sac0_45508_config3")]
pub mod sac0_45508_config3;
#[cfg(feature = "sac0_45508_config4")]
pub mod sac0_45508_config4;
#[cfg(feature = "sac1_45508_config3")]
pub mod sac1_45508_config3;
#[cfg(feature = "sac2_45508_config3")]
pub mod sac2_45508_config3;
#[cfg(feature = "sac3_45508_config3")]
pub mod sac3_45508_config3;
#[cfg(feature = "saph_3670")]
pub mod saph_3670;
#[cfg(feature = "saph_a_3670")]
pub mod saph_a_3670;
#[cfg(feature = "scan_interface_1")]
pub mod scan_interface_1;
#[cfg(feature = "sd14_module_1")]
pub mod sd14_module_1;
#[cfg(feature = "sd16_1")]
pub mod sd16_1;
#[cfg(feature = "sd16_2")]
pub mod sd16_2;
#[cfg(feature = "sd16_a1_1")]
pub mod sd16_a1_1;
#[cfg(feature = "sd16_a1_2")]
pub mod sd16_a1_2;
#[cfg(feature = "sd16_a1_3")]
pub mod sd16_a1_3;
#[cfg(feature = "sd16_a3_1")]
pub mod sd16_a3_1;
#[cfg(feature = "sd16_a3_2")]
pub mod sd16_a3_2;
#[cfg(feature = "sd16_a4_1")]
pub mod sd16_a4_1;
#[cfg(feature = "sd16_a6_1")]
pub mod sd16_a6_1;
#[cfg(feature = "sd16_a7_1")]
pub mod sd16_a7_1;
#[cfg(feature = "sd24_a1_1")]
pub mod sd24_a1_1;
#[cfg(feature = "sd24_a2_1")]
pub mod sd24_a2_1;
#[cfg(feature = "sd24_a2_2")]
pub mod sd24_a2_2;
#[cfg(feature = "sd24_a3_1")]
pub mod sd24_a3_1;
#[cfg(feature = "sd24_a3_2")]
pub mod sd24_a3_2;
#[cfg(feature = "sd24_a4_1")]
pub mod sd24_a4_1;
#[cfg(feature = "sd24_b2_1")]
pub mod sd24_b2_1;
#[cfg(feature = "sd24_b3_1")]
pub mod sd24_b3_1;
#[cfg(feature = "sd24_b3_2")]
pub mod sd24_b3_2;
#[cfg(feature = "sd24_b4_1")]
pub mod sd24_b4_1;
#[cfg(feature = "sd24_b6_1")]
pub mod sd24_b6_1;
#[cfg(feature = "sd24_b7_1")]
pub mod sd24_b7_1;
#[cfg(feature = "sdhs_3670")]
pub mod sdhs_3670;
#[cfg(feature = "sfr_2080")]
pub mod sfr_2080;
#[cfg(feature = "sfr_4450")]
pub mod sfr_4450;
#[cfg(feature = "sfr__special_function_registers_1")]
pub mod sfr__special_function_registers_1;
#[cfg(feature = "sfr__special_function_registers_2")]
pub mod sfr__special_function_registers_2;
#[cfg(feature = "sfr__special_function_registers_3")]
pub mod sfr__special_function_registers_3;
#[cfg(feature = "shared_reference_1")]
pub mod shared_reference_1;
#[cfg(feature = "shared_reference_2")]
pub mod shared_reference_2;
#[cfg(feature = "shared_reference_3")]
pub mod shared_reference_3;
#[cfg(feature = "special_function_1")]
pub mod special_function_1;
#[cfg(feature = "special_function_10")]
pub mod special_function_10;
#[cfg(feature = "special_function_11")]
pub mod special_function_11;
#[cfg(feature = "special_function_12")]
pub mod special_function_12;
#[cfg(feature = "special_function_13")]
pub mod special_function_13;
#[cfg(feature = "special_function_14")]
pub mod special_function_14;
#[cfg(feature = "special_function_15")]
pub mod special_function_15;
#[cfg(feature = "special_function_16")]
pub mod special_function_16;
#[cfg(feature = "special_function_17")]
pub mod special_function_17;
#[cfg(feature = "special_function_18")]
pub mod special_function_18;
#[cfg(feature = "special_function_19")]
pub mod special_function_19;
#[cfg(feature = "special_function_2")]
pub mod special_function_2;
#[cfg(feature = "special_function_20")]
pub mod special_function_20;
#[cfg(feature = "special_function_3")]
pub mod special_function_3;
#[cfg(feature = "special_function_4")]
pub mod special_function_4;
#[cfg(feature = "special_function_5")]
pub mod special_function_5;
#[cfg(feature = "special_function_6")]
pub mod special_function_6;
#[cfg(feature = "special_function_7")]
pub mod special_function_7;
#[cfg(feature = "special_function_8")]
pub mod special_function_8;
#[cfg(feature = "special_function_9")]
pub mod special_function_9;
#[cfg(feature = "supply_voltage_supervisor_1")]
pub mod supply_voltage_supervisor_1;
#[cfg(feature = "supply_voltage_supervisor_2")]
pub mod supply_voltage_supervisor_2;
#[cfg(feature = "sys_10")]
pub mod sys_10;
#[cfg(feature = "sys_2080")]
pub mod sys_2080;
#[cfg(feature = "sys_445")]
pub mod sys_445;
#[cfg(feature = "sys__system_module_1")]
pub mod sys__system_module_1;
#[cfg(feature = "sys__system_module_2")]
pub mod sys__system_module_2;
#[cfg(feature = "sys__system_module_3")]
pub mod sys__system_module_3;
#[cfg(feature = "sys__system_module_4")]
pub mod sys__system_module_4;
#[cfg(feature = "sys__system_module_5")]
pub mod sys__system_module_5;
#[cfg(feature = "sys__system_module_6")]
pub mod sys__system_module_6;
#[cfg(feature = "system_clock_1")]
pub mod system_clock_1;
#[cfg(feature = "system_clock_2")]
pub mod system_clock_2;
#[cfg(feature = "system_clock_3")]
pub mod system_clock_3;
#[cfg(feature = "system_clock_4")]
pub mod system_clock_4;
#[cfg(feature = "system_clock_5")]
pub mod system_clock_5;
#[cfg(feature = "system_clock_fllplus_1")]
pub mod system_clock_fllplus_1;
#[cfg(feature = "system_clock_fllplus_2")]
pub mod system_clock_fllplus_2;
#[cfg(feature = "system_clock_fllplus_3")]
pub mod system_clock_fllplus_3;
#[cfg(feature = "system_clock_fllplus_4")]
pub mod system_clock_fllplus_4;
#[cfg(feature = "system_clock_fllplus_5")]
pub mod system_clock_fllplus_5;
#[cfg(feature = "system_clock_fllplus_6")]
pub mod system_clock_fllplus_6;
#[cfg(feature = "ta0_3560_inst3")]
pub mod ta0_3560_inst3;
#[cfg(feature = "ta0_3560_inst7")]
pub mod ta0_3560_inst7;
#[cfg(feature = "ta1_3560_inst3")]
pub mod ta1_3560_inst3;
#[cfg(feature = "ta1_3560_inst7")]
pub mod ta1_3560_inst7;
#[cfg(feature = "ta2_3560_inst2")]
pub mod ta2_3560_inst2;
#[cfg(feature = "ta2_3560_inst3")]
pub mod ta2_3560_inst3;
#[cfg(feature = "ta3_3560_inst2")]
pub mod ta3_3560_inst2;
#[cfg(feature = "ta3_3560_inst3")]
pub mod ta3_3560_inst3;
#[cfg(feature = "ta4_3560_inst2")]
pub mod ta4_3560_inst2;
#[cfg(feature = "ta4_3560_inst3")]
pub mod ta4_3560_inst3;
#[cfg(feature = "tb0_3670_inst3")]
pub mod tb0_3670_inst3;
#[cfg(feature = "tb0_3670_inst7")]
pub mod tb0_3670_inst7;
#[cfg(feature = "tb1_3670_inst3")]
pub mod tb1_3670_inst3;
#[cfg(feature = "tb2_3670_inst3")]
pub mod tb2_3670_inst3;
#[cfg(feature = "tb3_3670_inst7")]
pub mod tb3_3670_inst7;
#[cfg(feature = "timer0_a3_1")]
pub mod timer0_a3_1;
#[cfg(feature = "timer0_a3_2")]
pub mod timer0_a3_2;
#[cfg(feature = "timer0_a3_4")]
pub mod timer0_a3_4;
#[cfg(feature = "timer0_a5_1")]
pub mod timer0_a5_1;
#[cfg(feature = "timer0_b3_1")]
pub mod timer0_b3_1;
#[cfg(feature = "timer0_b7_1")]
pub mod timer0_b7_1;
#[cfg(feature = "timer0_d3_1")]
pub mod timer0_d3_1;
#[cfg(feature = "timer1_a2_1")]
pub mod timer1_a2_1;
#[cfg(feature = "timer1_a2_2")]
pub mod timer1_a2_2;
#[cfg(feature = "timer1_a3_1")]
pub mod timer1_a3_1;
#[cfg(feature = "timer1_a3_2")]
pub mod timer1_a3_2;
#[cfg(feature = "timer1_a3_3")]
pub mod timer1_a3_3;
#[cfg(feature = "timer1_a3_4")]
pub mod timer1_a3_4;
#[cfg(feature = "timer1_a5_1")]
pub mod timer1_a5_1;
#[cfg(feature = "timer1_b3_1")]
pub mod timer1_b3_1;
#[cfg(feature = "timer1_d3_1")]
pub mod timer1_d3_1;
#[cfg(feature = "timer2_a2_1")]
pub mod timer2_a2_1;
#[cfg(feature = "timer2_a3_1")]
pub mod timer2_a3_1;
#[cfg(feature = "timer2_b3_1")]
pub mod timer2_b3_1;
#[cfg(feature = "timer3_a2_1")]
pub mod timer3_a2_1;
#[cfg(feature = "timer3_a5_1")]
pub mod timer3_a5_1;
#[cfg(feature = "timer_a2_1")]
pub mod timer_a2_1;
#[cfg(feature = "timer_a3_1")]
pub mod timer_a3_1;
#[cfg(feature = "timer_a5_1")]
pub mod timer_a5_1;
#[cfg(feature = "timer_b3_1")]
pub mod timer_b3_1;
#[cfg(feature = "timer_b7_1")]
pub mod timer_b7_1;
#[cfg(feature = "timer_event_control_1")]
pub mod timer_event_control_1;
#[cfg(feature = "timer_event_control_2")]
pub mod timer_event_control_2;
#[cfg(feature = "timer_port_1")]
pub mod timer_port_1;
#[cfg(feature = "tlv_calibration_data_1")]
pub mod tlv_calibration_data_1;
#[cfg(feature = "tlv_calibration_data_2")]
pub mod tlv_calibration_data_2;
#[cfg(feature = "tlv_calibration_data_3")]
pub mod tlv_calibration_data_3;
#[cfg(feature = "tri0_44508")]
pub mod tri0_44508;
#[cfg(feature = "uart_1")]
pub mod uart_1;
#[cfg(feature = "ucs__unified_system_clock_1")]
pub mod ucs__unified_system_clock_1;
#[cfg(feature = "ucs__unified_system_clock_2")]
pub mod ucs__unified_system_clock_2;
#[cfg(feature = "ucs__unified_system_clock_3")]
pub mod ucs__unified_system_clock_3;
#[cfg(feature = "ucs__unified_system_clock_4")]
pub mod ucs__unified_system_clock_4;
#[cfg(feature = "ucs__unified_system_clock_5")]
pub mod ucs__unified_system_clock_5;
#[cfg(feature = "ucs__unified_system_clock_6")]
pub mod ucs__unified_system_clock_6;
#[cfg(feature = "usart_0__i2c_mode_1")]
pub mod usart_0__i2c_mode_1;
#[cfg(feature = "usart_0__uart_spi_mode_1")]
pub mod usart_0__uart_spi_mode_1;
#[cfg(feature = "usart_1_1")]
pub mod usart_1_1;
#[cfg(feature = "usb_control_1")]
pub mod usb_control_1;
#[cfg(feature = "usb_operation_1")]
pub mod usb_operation_1;
#[cfg(feature = "usci_a0__spi_mode_1")]
pub mod usci_a0__spi_mode_1;
#[cfg(feature = "usci_a0__spi_mode_2")]
pub mod usci_a0__spi_mode_2;
#[cfg(feature = "usci_a0__spi_mode_3")]
pub mod usci_a0__spi_mode_3;
#[cfg(feature = "usci_a0__uart_mode_1")]
pub mod usci_a0__uart_mode_1;
#[cfg(feature = "usci_a0__uart_mode_2")]
pub mod usci_a0__uart_mode_2;
#[cfg(feature = "usci_a0__uart_mode_3")]
pub mod usci_a0__uart_mode_3;
#[cfg(feature = "usci_a1__spi_mode_1")]
pub mod usci_a1__spi_mode_1;
#[cfg(feature = "usci_a1__spi_mode_2")]
pub mod usci_a1__spi_mode_2;
#[cfg(feature = "usci_a1__spi_mode_3")]
pub mod usci_a1__spi_mode_3;
#[cfg(feature = "usci_a1__uart_mode_1")]
pub mod usci_a1__uart_mode_1;
#[cfg(feature = "usci_a1__uart_mode_2")]
pub mod usci_a1__uart_mode_2;
#[cfg(feature = "usci_a1__uart_mode_3")]
pub mod usci_a1__uart_mode_3;
#[cfg(feature = "usci_a2__spi_mode_1")]
pub mod usci_a2__spi_mode_1;
#[cfg(feature = "usci_a2__spi_mode_2")]
pub mod usci_a2__spi_mode_2;
#[cfg(feature = "usci_a2__uart_mode_1")]
pub mod usci_a2__uart_mode_1;
#[cfg(feature = "usci_a2__uart_mode_2")]
pub mod usci_a2__uart_mode_2;
#[cfg(feature = "usci_a3__spi_mode_1")]
pub mod usci_a3__spi_mode_1;
#[cfg(feature = "usci_a3__spi_mode_2")]
pub mod usci_a3__spi_mode_2;
#[cfg(feature = "usci_a3__uart_mode_1")]
pub mod usci_a3__uart_mode_1;
#[cfg(feature = "usci_a3__uart_mode_2")]
pub mod usci_a3__uart_mode_2;
#[cfg(feature = "usci_b0__i2c_mode_1")]
pub mod usci_b0__i2c_mode_1;
#[cfg(feature = "usci_b0__i2c_mode_2")]
pub mod usci_b0__i2c_mode_2;
#[cfg(feature = "usci_b0__i2c_mode_3")]
pub mod usci_b0__i2c_mode_3;
#[cfg(feature = "usci_b0__i2c_mode_4")]
pub mod usci_b0__i2c_mode_4;
#[cfg(feature = "usci_b0__spi_mode_1")]
pub mod usci_b0__spi_mode_1;
#[cfg(feature = "usci_b0__spi_mode_2")]
pub mod usci_b0__spi_mode_2;
#[cfg(feature = "usci_b0__spi_mode_3")]
pub mod usci_b0__spi_mode_3;
#[cfg(feature = "usci_b1__i2c_mode_1")]
pub mod usci_b1__i2c_mode_1;
#[cfg(feature = "usci_b1__i2c_mode_2")]
pub mod usci_b1__i2c_mode_2;
#[cfg(feature = "usci_b1__i2c_mode_3")]
pub mod usci_b1__i2c_mode_3;
#[cfg(feature = "usci_b1__spi_mode_1")]
pub mod usci_b1__spi_mode_1;
#[cfg(feature = "usci_b1__spi_mode_2")]
pub mod usci_b1__spi_mode_2;
#[cfg(feature = "usci_b1__spi_mode_3")]
pub mod usci_b1__spi_mode_3;
#[cfg(feature = "usci_b2__i2c_mode_1")]
pub mod usci_b2__i2c_mode_1;
#[cfg(feature = "usci_b2__spi_mode_1")]
pub mod usci_b2__spi_mode_1;
#[cfg(feature = "usci_b3__i2c_mode_1")]
pub mod usci_b3__i2c_mode_1;
#[cfg(feature = "usci_b3__spi_mode_1")]
pub mod usci_b3__spi_mode_1;
#[cfg(feature = "usi_1")]
pub mod usi_1;
#[cfg(feature = "uups_3670")]
pub mod uups_3670;
#[cfg(feature = "watchdog_timer_1")]
pub mod watchdog_timer_1;
#[cfg(feature = "watchdog_timer_2")]
pub mod watchdog_timer_2;
#[cfg(feature = "wdt_a_3560")]
pub mod wdt_a_3560;
