#[cfg(feature = "_8bit_timer_counter_1")]
pub mod _8bit_timer_counter_1;
#[cfg(feature = "adc10_2")]
pub mod adc10_2;
#[cfg(feature = "adc10_3")]
pub mod adc10_3;
#[cfg(feature = "adc10_ab")]
pub mod adc10_ab;
#[cfg(feature = "adc12_1")]
pub mod adc12_1;
#[cfg(feature = "adc12_2")]
pub mod adc12_2;
#[cfg(feature = "adc12_3")]
pub mod adc12_3;
#[cfg(feature = "adc12_b")]
pub mod adc12_b;
#[cfg(feature = "adc_1")]
pub mod adc_1;
#[cfg(feature = "adc_2")]
pub mod adc_2;
#[cfg(feature = "adc_3")]
pub mod adc_3;
#[cfg(feature = "aes256")]
pub mod aes256;
#[cfg(feature = "aes_accelerator_1")]
pub mod aes_accelerator_1;
#[cfg(feature = "aes_accelerator_2")]
pub mod aes_accelerator_2;
#[cfg(feature = "analog_pool")]
pub mod analog_pool;
#[cfg(feature = "auxilary_supply")]
pub mod auxilary_supply;
#[cfg(feature = "backup_memory")]
pub mod backup_memory;
#[cfg(feature = "backup_ram")]
pub mod backup_ram;
#[cfg(feature = "basic_timer")]
pub mod basic_timer;
#[cfg(feature = "basic_timer_rtc")]
pub mod basic_timer_rtc;
#[cfg(feature = "battery_charger")]
pub mod battery_charger;
#[cfg(feature = "calibration_data_1")]
pub mod calibration_data_1;
#[cfg(feature = "calibration_data_2")]
pub mod calibration_data_2;
#[cfg(feature = "calibration_data_3")]
pub mod calibration_data_3;
#[cfg(feature = "capacitive_touch_io")]
pub mod capacitive_touch_io;
#[cfg(feature = "captio")]
pub mod captio;
#[cfg(feature = "captivate")]
pub mod captivate;
#[cfg(feature = "cc1101")]
pub mod cc1101;
#[cfg(feature = "ccs")]
pub mod ccs;
#[cfg(feature = "comp_e")]
pub mod comp_e;
#[cfg(feature = "comparator_a_1")]
pub mod comparator_a_1;
#[cfg(feature = "comparator_a_2")]
pub mod comparator_a_2;
#[cfg(feature = "comparator_b")]
pub mod comparator_b;
#[cfg(feature = "comparator_d")]
pub mod comparator_d;
#[cfg(feature = "comparator_e")]
pub mod comparator_e;
#[cfg(feature = "crc16_1")]
pub mod crc16_1;
#[cfg(feature = "crc16_2")]
pub mod crc16_2;
#[cfg(feature = "crc32_1")]
pub mod crc32_1;
#[cfg(feature = "crc32_2")]
pub mod crc32_2;
#[cfg(feature = "cs_3670")]
pub mod cs_3670;
#[cfg(feature = "cs_445")]
pub mod cs_445;
#[cfg(feature = "cs_1")]
pub mod cs_1;
#[cfg(feature = "cs_2")]
pub mod cs_2;
#[cfg(feature = "cs_3")]
pub mod cs_3;
#[cfg(feature = "cs_4")]
pub mod cs_4;
#[cfg(feature = "cs_5")]
pub mod cs_5;
#[cfg(feature = "csys_1")]
pub mod csys_1;
#[cfg(feature = "csys_2")]
pub mod csys_2;
#[cfg(feature = "ctsd16_b4")]
pub mod ctsd16_b4;
#[cfg(feature = "dac12_1")]
pub mod dac12_1;
#[cfg(feature = "dac12_2")]
pub mod dac12_2;
#[cfg(feature = "dac12_3")]
pub mod dac12_3;
#[cfg(feature = "dac12_4")]
pub mod dac12_4;
#[cfg(feature = "dma_1")]
pub mod dma_1;
#[cfg(feature = "dma_10")]
pub mod dma_10;
#[cfg(feature = "dma_11")]
pub mod dma_11;
#[cfg(feature = "dma_12")]
pub mod dma_12;
#[cfg(feature = "dma_13")]
pub mod dma_13;
#[cfg(feature = "dma_14")]
pub mod dma_14;
#[cfg(feature = "dma_15")]
pub mod dma_15;
#[cfg(feature = "dma_16")]
pub mod dma_16;
#[cfg(feature = "dma_17")]
pub mod dma_17;
#[cfg(feature = "dma_18")]
pub mod dma_18;
#[cfg(feature = "dma_19")]
pub mod dma_19;
#[cfg(feature = "dma_2")]
pub mod dma_2;
#[cfg(feature = "dma_3")]
pub mod dma_3;
#[cfg(feature = "dma_4")]
pub mod dma_4;
#[cfg(feature = "dma_5")]
pub mod dma_5;
#[cfg(feature = "dma_6")]
pub mod dma_6;
#[cfg(feature = "dma_7")]
pub mod dma_7;
#[cfg(feature = "dma_8")]
pub mod dma_8;
#[cfg(feature = "dma_9")]
pub mod dma_9;
#[cfg(feature = "ecomp")]
pub mod ecomp;
#[cfg(feature = "eprom")]
pub mod eprom;
#[cfg(feature = "espctl_1")]
pub mod espctl_1;
#[cfg(feature = "espctl_2")]
pub mod espctl_2;
#[cfg(feature = "espctl_3")]
pub mod espctl_3;
#[cfg(feature = "eusci_a")]
pub mod eusci_a;
#[cfg(feature = "eusci_b")]
pub mod eusci_b;
#[cfg(feature = "extscanif")]
pub mod extscanif;
#[cfg(feature = "extscanif_ram")]
pub mod extscanif_ram;
#[cfg(feature = "flash_1")]
pub mod flash_1;
#[cfg(feature = "flash_2")]
pub mod flash_2;
#[cfg(feature = "flash_3")]
pub mod flash_3;
#[cfg(feature = "flash_4")]
pub mod flash_4;
#[cfg(feature = "flash_5")]
pub mod flash_5;
#[cfg(feature = "flash_6")]
pub mod flash_6;
#[cfg(feature = "flash_7")]
pub mod flash_7;
#[cfg(feature = "fram_1")]
pub mod fram_1;
#[cfg(feature = "fram_2")]
pub mod fram_2;
#[cfg(feature = "frctl")]
pub mod frctl;
#[cfg(feature = "frctl_a")]
pub mod frctl_a;
#[cfg(feature = "hspll")]
pub mod hspll;
#[cfg(feature = "icc")]
pub mod icc;
#[cfg(feature = "lcd_1")]
pub mod lcd_1;
#[cfg(feature = "lcd_2")]
pub mod lcd_2;
#[cfg(feature = "lcd_a_1")]
pub mod lcd_a_1;
#[cfg(feature = "lcd_b_1")]
pub mod lcd_b_1;
#[cfg(feature = "lcd_c_1")]
pub mod lcd_c_1;
#[cfg(feature = "lcd_c_2")]
pub mod lcd_c_2;
#[cfg(feature = "lcd_c_3")]
pub mod lcd_c_3;
#[cfg(feature = "lcd_e_1")]
pub mod lcd_e_1;
#[cfg(feature = "lea")]
pub mod lea;
#[cfg(feature = "mpu_1")]
pub mod mpu_1;
#[cfg(feature = "mpu_2")]
pub mod mpu_2;
#[cfg(feature = "mpu_3")]
pub mod mpu_3;
#[cfg(feature = "mpy32")]
pub mod mpy32;
#[cfg(feature = "mpy_16")]
pub mod mpy_16;
#[cfg(feature = "mpy_32")]
pub mod mpy_32;
#[cfg(feature = "mtif")]
pub mod mtif;
#[cfg(feature = "multiplier")]
pub mod multiplier;
#[cfg(feature = "multiplier_16")]
pub mod multiplier_16;
#[cfg(feature = "multiplier_32")]
pub mod multiplier_32;
#[cfg(feature = "operational_amplifier")]
pub mod operational_amplifier;
#[cfg(feature = "operational_amplifier_1")]
pub mod operational_amplifier_1;
#[cfg(feature = "operational_amplifier_2")]
pub mod operational_amplifier_2;
#[cfg(feature = "operational_amplifier_3")]
pub mod operational_amplifier_3;
#[cfg(feature = "operational_amplifier_4")]
pub mod operational_amplifier_4;
#[cfg(feature = "pmm_3670")]
pub mod pmm_3670;
#[cfg(feature = "pmm_445")]
pub mod pmm_445;
#[cfg(feature = "pmm_45")]
pub mod pmm_45;
#[cfg(feature = "pmm_1")]
pub mod pmm_1;
#[cfg(feature = "pmm_2")]
pub mod pmm_2;
#[cfg(feature = "pmm_3")]
pub mod pmm_3;
#[cfg(feature = "pmm_4")]
pub mod pmm_4;
#[cfg(feature = "pmm_5")]
pub mod pmm_5;
#[cfg(feature = "pmm_6")]
pub mod pmm_6;
#[cfg(feature = "pmm_7")]
pub mod pmm_7;
#[cfg(feature = "port_0_1")]
pub mod port_0_1;
#[cfg(feature = "port_12_1")]
pub mod port_12_1;
#[cfg(feature = "port_12_2")]
pub mod port_12_2;
#[cfg(feature = "port_1_1")]
pub mod port_1_1;
#[cfg(feature = "port_1_2")]
pub mod port_1_2;
#[cfg(feature = "port_2_1")]
pub mod port_2_1;
#[cfg(feature = "port_3_1")]
pub mod port_3_1;
#[cfg(feature = "port_3_2")]
pub mod port_3_2;
#[cfg(feature = "port_4_1")]
pub mod port_4_1;
#[cfg(feature = "port_4_2")]
pub mod port_4_2;
#[cfg(feature = "port_5_1")]
pub mod port_5_1;
#[cfg(feature = "port_6_1")]
pub mod port_6_1;
#[cfg(feature = "port_78")]
pub mod port_78;
#[cfg(feature = "port_910")]
pub mod port_910;
#[cfg(feature = "port_a")]
pub mod port_a;
#[cfg(feature = "port_ab")]
pub mod port_ab;
#[cfg(feature = "port_b")]
pub mod port_b;
#[cfg(feature = "port_j_1")]
pub mod port_j_1;
#[cfg(feature = "port_j_2")]
pub mod port_j_2;
#[cfg(feature = "port_j_3")]
pub mod port_j_3;
#[cfg(feature = "port_j_4")]
pub mod port_j_4;
#[cfg(feature = "port_j_5")]
pub mod port_j_5;
#[cfg(feature = "port_x_1")]
pub mod port_x_1;
#[cfg(feature = "port_x_2")]
pub mod port_x_2;
#[cfg(feature = "portb_1")]
pub mod portb_1;
#[cfg(feature = "portb_1i1")]
pub mod portb_1i1;
#[cfg(feature = "portb_1i2")]
pub mod portb_1i2;
#[cfg(feature = "portb_2")]
pub mod portb_2;
#[cfg(feature = "portb_2i1")]
pub mod portb_2i1;
#[cfg(feature = "portb_2i2")]
pub mod portb_2i2;
#[cfg(feature = "portb_3")]
pub mod portb_3;
#[cfg(feature = "portb_3i")]
pub mod portb_3i;
#[cfg(feature = "portb_3i1")]
pub mod portb_3i1;
#[cfg(feature = "portb_3i2")]
pub mod portb_3i2;
#[cfg(feature = "portb_4i1")]
pub mod portb_4i1;
#[cfg(feature = "portb_4i2")]
pub mod portb_4i2;
#[cfg(feature = "portb_5")]
pub mod portb_5;
#[cfg(feature = "portb_5i1")]
pub mod portb_5i1;
#[cfg(feature = "portb_5i2")]
pub mod portb_5i2;
#[cfg(feature = "portb_6")]
pub mod portb_6;
#[cfg(feature = "portb_6i1")]
pub mod portb_6i1;
#[cfg(feature = "portb_6i2")]
pub mod portb_6i2;
#[cfg(feature = "portw_1")]
pub mod portw_1;
#[cfg(feature = "portw_1i")]
pub mod portw_1i;
#[cfg(feature = "portw_2")]
pub mod portw_2;
#[cfg(feature = "portw_2i")]
pub mod portw_2i;
#[cfg(feature = "portw_3")]
pub mod portw_3;
#[cfg(feature = "portw_3i")]
pub mod portw_3i;
#[cfg(feature = "portw_4i")]
pub mod portw_4i;
#[cfg(feature = "portw_5")]
pub mod portw_5;
#[cfg(feature = "portw_5i")]
pub mod portw_5i;
#[cfg(feature = "portw_6")]
pub mod portw_6;
#[cfg(feature = "portw_6i")]
pub mod portw_6i;
#[cfg(feature = "port_mapping_control")]
pub mod port_mapping_control;
#[cfg(feature = "port_mapping")]
pub mod port_mapping;
#[cfg(feature = "port_u_control")]
pub mod port_u_control;
#[cfg(feature = "ramctl_1")]
pub mod ramctl_1;
#[cfg(feature = "ramctl_2")]
pub mod ramctl_2;
#[cfg(feature = "rc_1")]
pub mod rc_1;
#[cfg(feature = "rc_2")]
pub mod rc_2;
#[cfg(feature = "rc_fram")]
pub mod rc_fram;
#[cfg(feature = "realtime_clock")]
pub mod realtime_clock;
#[cfg(feature = "ref_a")]
pub mod ref_a;
#[cfg(feature = "rf13m")]
pub mod rf13m;
#[cfg(feature = "rtc_445")]
pub mod rtc_445;
#[cfg(feature = "rtc_1")]
pub mod rtc_1;
#[cfg(feature = "rtc_b")]
pub mod rtc_b;
#[cfg(feature = "rtc_c_2080")]
pub mod rtc_c_2080;
#[cfg(feature = "rtc_c_1")]
pub mod rtc_c_1;
#[cfg(feature = "rtc_c_2")]
pub mod rtc_c_2;
#[cfg(feature = "rtc_c_3")]
pub mod rtc_c_3;
#[cfg(feature = "rtc_ce_1")]
pub mod rtc_ce_1;
#[cfg(feature = "rtc_ce_2")]
pub mod rtc_ce_2;
#[cfg(feature = "rtc_d")]
pub mod rtc_d;
#[cfg(feature = "sac_1")]
pub mod sac_1;
#[cfg(feature = "sac_3")]
pub mod sac_3;
#[cfg(feature = "sac_4")]
pub mod sac_4;
#[cfg(feature = "saph")]
pub mod saph;
#[cfg(feature = "saph_a")]
pub mod saph_a;
#[cfg(feature = "scan_interface")]
pub mod scan_interface;
#[cfg(feature = "sd14_module_1")]
pub mod sd14_module_1;
#[cfg(feature = "sd16_1")]
pub mod sd16_1;
#[cfg(feature = "sd16_2")]
pub mod sd16_2;
#[cfg(feature = "sd16_a1_1")]
pub mod sd16_a1_1;
#[cfg(feature = "sd16_a1_2")]
pub mod sd16_a1_2;
#[cfg(feature = "sd16_a1_3")]
pub mod sd16_a1_3;
#[cfg(feature = "sd16_a3_1")]
pub mod sd16_a3_1;
#[cfg(feature = "sd16_a3_2")]
pub mod sd16_a3_2;
#[cfg(feature = "sd16_a4_1")]
pub mod sd16_a4_1;
#[cfg(feature = "sd16_a6_1")]
pub mod sd16_a6_1;
#[cfg(feature = "sd16_a7_1")]
pub mod sd16_a7_1;
#[cfg(feature = "sd24_a1_1")]
pub mod sd24_a1_1;
#[cfg(feature = "sd24_a2_1")]
pub mod sd24_a2_1;
#[cfg(feature = "sd24_a2_2")]
pub mod sd24_a2_2;
#[cfg(feature = "sd24_a3_1")]
pub mod sd24_a3_1;
#[cfg(feature = "sd24_a3_2")]
pub mod sd24_a3_2;
#[cfg(feature = "sd24_a4_1")]
pub mod sd24_a4_1;
#[cfg(feature = "sd24_b2_1")]
pub mod sd24_b2_1;
#[cfg(feature = "sd24_b3_1")]
pub mod sd24_b3_1;
#[cfg(feature = "sd24_b3_2")]
pub mod sd24_b3_2;
#[cfg(feature = "sd24_b4_1")]
pub mod sd24_b4_1;
#[cfg(feature = "sd24_b6_1")]
pub mod sd24_b6_1;
#[cfg(feature = "sd24_b7_1")]
pub mod sd24_b7_1;
#[cfg(feature = "sdhs_3670")]
pub mod sdhs_3670;
#[cfg(feature = "sfr_1")]
pub mod sfr_1;
#[cfg(feature = "sfr_2")]
pub mod sfr_2;
#[cfg(feature = "sfr_3")]
pub mod sfr_3;
#[cfg(feature = "sfr_4")]
pub mod sfr_4;
#[cfg(feature = "shared_reference_1")]
pub mod shared_reference_1;
#[cfg(feature = "shared_reference_2")]
pub mod shared_reference_2;
#[cfg(feature = "shared_reference_3")]
pub mod shared_reference_3;
#[cfg(feature = "special_function_1")]
pub mod special_function_1;
#[cfg(feature = "special_function_10")]
pub mod special_function_10;
#[cfg(feature = "special_function_11")]
pub mod special_function_11;
#[cfg(feature = "special_function_12")]
pub mod special_function_12;
#[cfg(feature = "special_function_13")]
pub mod special_function_13;
#[cfg(feature = "special_function_14")]
pub mod special_function_14;
#[cfg(feature = "special_function_15")]
pub mod special_function_15;
#[cfg(feature = "special_function_16")]
pub mod special_function_16;
#[cfg(feature = "special_function_17")]
pub mod special_function_17;
#[cfg(feature = "special_function_18")]
pub mod special_function_18;
#[cfg(feature = "special_function_19")]
pub mod special_function_19;
#[cfg(feature = "special_function_2")]
pub mod special_function_2;
#[cfg(feature = "special_function_20")]
pub mod special_function_20;
#[cfg(feature = "special_function_3")]
pub mod special_function_3;
#[cfg(feature = "special_function_4")]
pub mod special_function_4;
#[cfg(feature = "special_function_5")]
pub mod special_function_5;
#[cfg(feature = "special_function_6")]
pub mod special_function_6;
#[cfg(feature = "special_function_7")]
pub mod special_function_7;
#[cfg(feature = "special_function_8")]
pub mod special_function_8;
#[cfg(feature = "special_function_9")]
pub mod special_function_9;
#[cfg(feature = "supply_voltage_supervisor_1")]
pub mod supply_voltage_supervisor_1;
#[cfg(feature = "supply_voltage_supervisor_2")]
pub mod supply_voltage_supervisor_2;
#[cfg(feature = "sys_10")]
pub mod sys_10;
#[cfg(feature = "sys_2080")]
pub mod sys_2080;
#[cfg(feature = "sys_445")]
pub mod sys_445;
#[cfg(feature = "sys_1")]
pub mod sys_1;
#[cfg(feature = "sys_2")]
pub mod sys_2;
#[cfg(feature = "sys_3")]
pub mod sys_3;
#[cfg(feature = "sys_4")]
pub mod sys_4;
#[cfg(feature = "sys_5")]
pub mod sys_5;
#[cfg(feature = "sys_6")]
pub mod sys_6;
#[cfg(feature = "system_clock_1")]
pub mod system_clock_1;
#[cfg(feature = "system_clock_2")]
pub mod system_clock_2;
#[cfg(feature = "system_clock_3")]
pub mod system_clock_3;
#[cfg(feature = "system_clock_5")]
pub mod system_clock_5;
#[cfg(feature = "system_clock_fllplus_1")]
pub mod system_clock_fllplus_1;
#[cfg(feature = "system_clock_fllplus_2")]
pub mod system_clock_fllplus_2;
#[cfg(feature = "system_clock_fllplus_3")]
pub mod system_clock_fllplus_3;
#[cfg(feature = "system_clock_fllplus_4")]
pub mod system_clock_fllplus_4;
#[cfg(feature = "system_clock_fllplus_5")]
pub mod system_clock_fllplus_5;
#[cfg(feature = "system_clock_fllplus_6")]
pub mod system_clock_fllplus_6;
#[cfg(feature = "ta_2")]
pub mod ta_2;
#[cfg(feature = "ta_3")]
pub mod ta_3;
#[cfg(feature = "ta_7")]
pub mod ta_7;
#[cfg(feature = "tb_3")]
pub mod tb_3;
#[cfg(feature = "tb_7")]
pub mod tb_7;
#[cfg(feature = "timer_a2_1")]
pub mod timer_a2_1;
#[cfg(feature = "timer_a3_1")]
pub mod timer_a3_1;
#[cfg(feature = "timer_a5_1")]
pub mod timer_a5_1;
#[cfg(feature = "timer_b3_1")]
pub mod timer_b3_1;
#[cfg(feature = "timer_b7_1")]
pub mod timer_b7_1;
#[cfg(feature = "timer_d3_1")]
pub mod timer_d3_1;
#[cfg(feature = "timer_a2_2")]
pub mod timer_a2_2;
#[cfg(feature = "timer_a3_2")]
pub mod timer_a3_2;
#[cfg(feature = "timer_a5_2")]
pub mod timer_a5_2;
#[cfg(feature = "timer_b3_2")]
pub mod timer_b3_2;
#[cfg(feature = "timer_a2_3")]
pub mod timer_a2_3;
#[cfg(feature = "timer_a3_3")]
pub mod timer_a3_3;
#[cfg(feature = "timer_a5_3")]
pub mod timer_a5_3;
#[cfg(feature = "timer_a3_4")]
pub mod timer_a3_4;
#[cfg(feature = "timer_event_control")]
pub mod timer_event_control;
#[cfg(feature = "timer_port")]
pub mod timer_port;
#[cfg(feature = "tlv_calibration_data_1")]
pub mod tlv_calibration_data_1;
#[cfg(feature = "tlv_calibration_data_2")]
pub mod tlv_calibration_data_2;
#[cfg(feature = "tlv_calibration_data_3")]
pub mod tlv_calibration_data_3;
#[cfg(feature = "tri0")]
pub mod tri0;
#[cfg(feature = "ucs_1")]
pub mod ucs_1;
#[cfg(feature = "ucs_2")]
pub mod ucs_2;
#[cfg(feature = "ucs_3")]
pub mod ucs_3;
#[cfg(feature = "ucs_5")]
pub mod ucs_5;
#[cfg(feature = "ucs_6")]
pub mod ucs_6;
#[cfg(feature = "usart")]
pub mod usart;
#[cfg(feature = "usart_i2c")]
pub mod usart_i2c;
#[cfg(feature = "usb_control")]
pub mod usb_control;
#[cfg(feature = "usb_operation")]
pub mod usb_operation;
#[cfg(feature = "usci_a_spi_1")]
pub mod usci_a_spi_1;
#[cfg(feature = "usci_a_spi_2")]
pub mod usci_a_spi_2;
#[cfg(feature = "usci_a_spi_3")]
pub mod usci_a_spi_3;
#[cfg(feature = "usci_a_uart_1")]
pub mod usci_a_uart_1;
#[cfg(feature = "usci_a_uart_2")]
pub mod usci_a_uart_2;
#[cfg(feature = "usci_a_uart_3")]
pub mod usci_a_uart_3;
#[cfg(feature = "usci_b_i2c_1")]
pub mod usci_b_i2c_1;
#[cfg(feature = "usci_b_i2c_2")]
pub mod usci_b_i2c_2;
#[cfg(feature = "usci_b_i2c_3")]
pub mod usci_b_i2c_3;
#[cfg(feature = "usci_b_i2c_4")]
pub mod usci_b_i2c_4;
#[cfg(feature = "usci_b_i2c_5")]
pub mod usci_b_i2c_5;
#[cfg(feature = "usci_b_spi_1")]
pub mod usci_b_spi_1;
#[cfg(feature = "usci_b_spi_2")]
pub mod usci_b_spi_2;
#[cfg(feature = "usci_b_spi_3")]
pub mod usci_b_spi_3;
#[cfg(feature = "usi")]
pub mod usi;
#[cfg(feature = "uups")]
pub mod uups;
#[cfg(feature = "watchdog_timer_1")]
pub mod watchdog_timer_1;
#[cfg(feature = "watchdog_timer_2")]
pub mod watchdog_timer_2;
#[cfg(feature = "wdt_a")]
pub mod wdt_a;
